spring.application.name=demo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Környezeti változók az adatbázishoz
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/datemaker_db?serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.address=0.0.0.0
server.port=8080

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd

# Email beállítások
spring.mail.host=smtp.gmail.com
spring.mail.port=587    
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

app.email.verification.code-ttl-minutes=10
app.email.verification.resend-cooldown-seconds=60
app.email.from=DateMaker <${MAIL_USERNAME}>

# Külső API kulcsok
google.recaptcha.secret=${RECAPTCHA_SECRET}
facebook.app-id=${FB_APP_ID}
facebook.app-secret=${FB_APP_SECRET}

logging.level.com.example.demo=INFO
logging.level.org.springframework.web=INFO
logging.level.com.example.demo.service.FacebookVerificationService=DEBUG

# Lokális útvonal (érdemes ezt is változóba tenni, mert szerveren más lesz)
app.avatar.dir=${AVATAR_DIR:C:/demo/avatars}
app.avatar.url-prefix=/avatars

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# JWT Titkosítás
app.jwt.secret=${JWT_SECRET}

# Twilio & Groq
twilio.account-sid=${TWILIO_SID}
twilio.auth-token=${TWILIO_TOKEN}
twilio.from-number=${TWILIO_NUMBER}

groq.api.key=${GROQ_API_KEY}
groq.model=llama-3.3-70b-versatile

server.forward-headers-strategy=framework